In [1]:
import numpy as np
import tensorflow as tf

## Membuat tensor shape (5,5) dengan nilai random = variable random_tensor

In [4]:
random_tensor = tf.Variable(tf.random.normal([5,5], mean=0, stddev=1, dtype=tf.float32, seed=1))
random_tensor.numpy()

array([[-0.28433853,  0.8922832 ,  0.8983451 ,  0.7163981 ,  0.34969485],
       [-0.37960768,  0.01531979,  0.27423722, -2.214901  , -0.08514621],
       [ 1.0113182 ,  0.6616626 ,  1.383323  , -0.40465203,  0.86142987],
       [-0.12589967, -1.418615  ,  2.0295074 ,  0.15304402,  0.13658497],
       [-0.49787143,  0.38847125, -0.4244715 ,  0.46214256, -0.5444318 ]],
      dtype=float32)

## Membuat tensor shape (5,5) dengan nilai bilangan prima = variable prime_tensor

In [7]:
listprima = [[2,3,5,7,11],[13,17,19,23,29],[31,37,41,43,47],[53,59,61,67,71],[73,79,83,89,97]]

prime_tensor = tf.Variable((tf.convert_to_tensor(listprima, dtype=tf.float32)))
prime_tensor.numpy()

array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]], dtype=float32)

## Mempilkan dimensi dua variabel di atas

In [8]:
print(random_tensor.shape)
print(prime_tensor.shape)

(5, 5)
(5, 5)


## PERHITUNGAN ARITMETIKA

## Penjumlahan

In [9]:
print(tf.add(random_tensor, prime_tensor))

tf.Tensor(
[[ 1.7156615  3.8922832  5.898345   7.7163982 11.349695 ]
 [12.620392  17.01532   19.274237  20.785099  28.914854 ]
 [32.01132   37.661663  42.383324  42.59535   47.86143  ]
 [52.8741    57.581387  63.029507  67.153046  71.13658  ]
 [72.50213   79.38847   82.57553   89.46214   96.45557  ]], shape=(5, 5), dtype=float32)


## Pengurangan

In [10]:
print(tf.subtract(random_tensor, prime_tensor))

tf.Tensor(
[[ -2.2843385  -2.1077168  -4.101655   -6.2836018 -10.650305 ]
 [-13.379608  -16.98468   -18.725763  -25.214901  -29.085146 ]
 [-29.988682  -36.338337  -39.616676  -43.40465   -46.13857  ]
 [-53.1259    -60.418613  -58.970493  -66.846954  -70.86342  ]
 [-73.49787   -78.61153   -83.42447   -88.53786   -97.54443  ]], shape=(5, 5), dtype=float32)


## Perkalian

In [11]:
print(tf.multiply(random_tensor, prime_tensor))

tf.Tensor(
[[ -0.56867707   2.6768496    4.4917254    5.0147867    3.8466434 ]
 [ -4.9349       0.2604365    5.210507   -50.942722    -2.4692402 ]
 [ 31.350864    24.481516    56.71624    -17.400038    40.487206  ]
 [ -6.672683   -83.69828    123.79995     10.253949     9.697533  ]
 [-36.344616    30.689228   -35.231133    41.130688   -52.809887  ]], shape=(5, 5), dtype=float32)


## Pembagian

In [12]:
print(tf.divide(random_tensor, prime_tensor))

tf.Tensor(
[[-0.14216927  0.29742774  0.17966902  0.10234259  0.03179044]
 [-0.02920059  0.00090116  0.01443354 -0.09630004 -0.00293608]
 [ 0.03262317  0.01788277  0.03373959 -0.00941051  0.0183283 ]
 [-0.00237547 -0.02404432  0.03327061  0.00228424  0.00192373]
 [-0.00682016  0.00491736 -0.00511411  0.00519261 -0.0056127 ]], shape=(5, 5), dtype=float32)


## Pemangkatan

In [13]:
print(tf.pow(random_tensor, prime_tensor))

tf.Tensor(
[[ 8.08484033e-02  7.10408509e-01  5.85081041e-01  9.68458578e-02
   9.56272288e-06]
 [-3.39902863e-06  1.41026244e-31  2.11057803e-11 -8.77302160e+07
  -9.43614219e-32]
 [ 1.41749847e+00  2.30968737e-07  5.99607312e+05 -1.27207896e-17
   9.02270083e-04]
 [-0.00000000e+00 -9.12027648e+08  5.63415762e+18  0.00000000e+00
   0.00000000e+00]
 [-7.75453741e-23  3.62536196e-33 -1.29249318e-31  1.46238155e-30
  -2.43510900e-26]], shape=(5, 5), dtype=float32)


## Menampilkan nilai max dan min dari variabel random tensor

In [14]:
print("Nilai Max bedasarkan kolom : ",tf.argmax(random_tensor, axis=0).numpy())

Nilai Max bedasarkan kolom :  [2 0 3 0 2]


In [16]:
tf.argmax(random_tensor, axis=0).numpy()

array([2, 0, 3, 0, 2], dtype=int64)

In [19]:
print("Nilai Max bedasarkan baris : ",tf.argmax(random_tensor, axis=1).numpy())

Nilai Max bedasarkan baris :  [2 2 2 2 3]


In [21]:
print("Nilai min bedasarkan kolom : ",tf.argmin(random_tensor, axis=0).numpy())

Nilai min bedasarkan kolom :  [4 3 4 1 4]


In [22]:
print("Nilai min bedasarkan baris : ",tf.argmin(random_tensor, axis=1).numpy())

Nilai min bedasarkan baris :  [0 3 3 1 4]


## Menampikan hasil penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [24]:
print(f"Size Awal Sebelum Concat : {random_tensor.shape} {prime_tensor.shape}" )

Size Awal Sebelum Concat : (5, 5) (5, 5)


In [26]:
concat_tensor_1 = tf.concat([random_tensor, prime_tensor], axis=0)
concat_tensor_2 = tf.concat([random_tensor, prime_tensor], axis=1)
print(f"Size yang sudah di concat kolom (axis = 0) : {concat_tensor_1.shape}")
print(f"Size yang sudah di concat baris (axis = 1) : {concat_tensor_2.shape}")

Size yang sudah di concat kolom (axis = 0) : (10, 5)
Size yang sudah di concat baris (axis = 1) : (5, 10)


## Menampilkan hasil sorting secara descending dari dua variabel diatas

In [27]:
print(tf.sort(random_tensor, direction="DESCENDING"))

tf.Tensor(
[[ 0.8983451   0.8922832   0.7163981   0.34969485 -0.28433853]
 [ 0.27423722  0.01531979 -0.08514621 -0.37960768 -2.214901  ]
 [ 1.383323    1.0113182   0.86142987  0.6616626  -0.40465203]
 [ 2.0295074   0.15304402  0.13658497 -0.12589967 -1.418615  ]
 [ 0.46214256  0.38847125 -0.4244715  -0.49787143 -0.5444318 ]], shape=(5, 5), dtype=float32)


In [28]:

print(tf.sort(prime_tensor, direction="DESCENDING"))

tf.Tensor(
[[11.  7.  5.  3.  2.]
 [29. 23. 19. 17. 13.]
 [47. 43. 41. 37. 31.]
 [71. 67. 61. 59. 53.]
 [97. 89. 83. 79. 73.]], shape=(5, 5), dtype=float32)
